#! /bin/sh
#
# Install opam, ocaml compilers and standard library.
# From https://github.com/mjambon/setup-ocaml
#
set -eux

mkdir -p .ssh
chmod 700 .ssh

if [ -z "$(git config user.email)" ]; then
  git config --global user.email "docker@example.com"
  git config --global user.name "Docker"
fi

opam init --disable-sandboxing -v
opam switch create "$@" -v

# update opam to have the latest packages before installing
opam update

cat >> ~/.bashrc <<"EOF"
# From https://github.com/semgrep/ocaml-layer
echo 'Running "eval $(opam env)", which initializes PATH and other variables.'
echo
echo 'In scripts and dockerfiles, don't forget to run your commands as
echo '  opam exec -- COMMAND'
echo 'or equivalently as'
echo '  eval $(opam env) && COMMAND'
echo
eval $(opam env)
EOF
