#! /bin/sh
#
# General system setup for Ubuntu prior to installing Opam.
# From https://github.com/mjambon/setup-ocaml
#
set -eux

# The command line arguments are a list of extra packages to install.
extra_packages=$*

apt-get update

packages="
  bubblewrap
  build-essential
  curl
  git
  libcap-dev
  libx11-dev
  nano
  opam
  python3-pip
  rsync
  sudo
  unzip
  $extra_packages
"

DEBIAN_FRONTEND=noninteractive apt-get install -y $packages

# no deb package for these
pip3 install --no-cache-dir pre-commit pipenv

if [ -z "$(git config user.email)" ]; then
  git config --global user.email "docker@example.com"
  git config --global user.name "Docker"
fi
